### ISSUE TITLE
Create concept art for the hunter.

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#15]
### Description

Information about the hunter can be found in the following link https://github.com/alexitsios/Calamity/wiki/Game-Design#the-hunter

### Acceptance Criteria: 

- Height: ~at least 2.5k pixels.
- PNG format with transparent background.
- The haracter sprite should have front, back, and side view.

**Comment by Skaers** [comment]
Regarding the height, are you referring to the size of the file? I was also curious about the alpha background: is it for helping the 3d artists during modeling?

**Comment by alexitsios** [comment]
Can you define what the Alpha background is? I don't know much about art ^ ^

Regarding the height, I placed this there as a placeholder. How much do you think it should be?

**Comment by Skaers** [comment]
> Can you define what the Alpha background is? I don't know much about art ^ ^
> 
> Regarding the height, I placed this there as a placeholder. How much do you think it should be?

Ah alright, well for concepting we focus on shape language, visuals and colours, and when it gets approved, if needed I make a character sheet (front, back, side pose), but it's up to the 3d artist, because most of the times he can still model after the accepted concept document. If you approve this method I'll start asap, tell me if there's any additional info anytime

**Comment by alexitsios** [comment]
I think you can go ahead for now since you're more experienced. Changes will happen one way or another till the final version.

**Comment by alexitsios** [comment]
@josschi95 please resolve this one as completed.
