### ISSUE TITLE
Flesh out transitions between scenes/exit door

### ISSUE THREAD

**Issue by crtherin** [alexitsios/Calamity#189]
### Description

Work out transitions between scenes and exit door

### Acceptance Criteria:

Mechanics and details written up, documented, and introduced into the wiki

**Comment by alexitsios** [comment]
@crtherin can you also include the template with the mechanics I provided in the example?

**Comment by teberzin** [comment]
**Design Title: Scene Transition**

**Design Description:** This design focuses that what will happen when the player interacts with the object that will move the player from one location to another (such as doors, stairs, elevators, etc.)

**Front-End Gameplay:**

- The game screen needs to freeze and fade in when the player interacts with the object that will move the player from one location to another (I will call it door from now on).
- When fading in is finished, the new scene has to start with a fade out. 

**Note:** We can make it super slow motion + zoom instead of just freezing (if it will be easy to do.)

**Back-End Functionality:**

- The player has to interact with the door. 
- After the interaction, the fade-in and fade-out process will start automatically. 
- During the fade-in and out section the player can't control the character (since the game will freeze.)

**Additional Content and Assets:**

- We don't need any extra assets for standard fade-in and out.
- (If we decide to make it zoom-in) We may need some zoom-in animation (like motion blur shader (if needed not sure about that, Jonathan can answer it better).).
- If we're going to add zoom-in, motion blur we might need sfx for it.

**Success and Fail States:**

If, when the player interacts with the door there's a transition sequence it's a success.

**Comment by teberzin** [comment]
Before adding it to the wiki, I want to ensure it fulfills the needs.

**Comment by alexitsios** [comment]
@teberzin  I did some research regarding transitions, and we'll probably have 4 cases:

1. Door / Elevator Transition: When the player character approaches and interacts with a door/elevator, the camera might cut to a quick fade to black screen. The player is transitioned to the new location.
2. Stair Transition: I'm not sure if this is going to be a transition or the player will be able to climb the stairs using normal controls. I'm in favor of this but we might need extra animation support, so we might consider a fade to black transition for now.
3. Fixed Camera Angle Transition: When the player character moves out of one fixed camera angle area and into another, the camera will switch to the new angle area without any fades.
4. Hidden transitions:  In some cases, the transition between areas might be hidden from the player. For example, the player might move through a narrow tunnel or enter a corridor that leads to a new area.

I'm in favor of having the player climb the stairs, but I fear we'll need extra animation support, so the alternative I'm thinking is to have the same door/elevator transition or omit any stair transition except for when the player goes to the roof. There we'll probably need to have a door/elevator transition because you're transferred to a whole new location.

@mashewmake do you think we could avoid stairs in general -- except for when going to the roof? It'd save us some time I think.

fyi @seekeroftheball @essothesquid @multihaxzors

**Comment by seekeroftheball** [comment]
We should avoid stairs and verticality as we don't actually use gravity at all in the game so that will require a decent amount of extra programming - or preset animations - such as, the player touches the start of the stairs, we disable player controls, and activate a fixed animation of them going up or down. It would be easier to omit this entirely if possible.

@alexitsios @mashewmake @teberzin @essothesquid @multihaxzors
