### ISSUE TITLE
Create a demo video to show the animation of the characters

### ISSUE THREAD

**Issue by Unicornosplendente** [alexitsios/Calamity#196]
### Descriptions
Demo videos, containing all animations of all characters & all creatures.

### Acceptance criteria:
- All animations of all characters/creatures have been uploaded as a video into the Asset Reference Google Drive Folder here https://drive.google.com/drive/u/0/folders/1swgWYBPKXBwMsfUqrWMHmwgR9oI-tFK4 
- Each animation has its own separate video.

**Comment by alexitsios** [comment]
@essothesquid 

The audio department needs video animations of all characters / creatures so that they can start working on the SFX. They'll need each animation per character as a separate video so that it's easy for them to find these references.


@ZidM @Unicornosplendente @multihaxzors @crtherin FYI

**Comment by essothesquid** [comment]
@alexitsios sounds good, I'll work on that soon

**Comment by Unicornosplendente** [comment]
@essothesquid is this finished :)?

fyi @alexitsios

**Comment by essothesquid** [comment]
@Unicornosplendente yes, they're in the drive folder that was linked in the original descrption. it's not marked as finished because I haven't finished the model of Athena, so I still have to animate and record that one too. but I have all of the other characters done.
