### ISSUE TITLE
Define the different types of collectibles that will be available in the game (e.g. diary pages, hidden keys, etc.).

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#34]

**Comment by alexitsios** [comment]
@teberzin I added myself here as well.

**Comment by alexitsios** [comment]
@ChristosDav @FreelanceSeven  I'm including you in this as well since the narrative beats will define the above.

**Comment by teberzin** [comment]
@ChristosDav @FreelanceSeven Any input for this?

**Comment by ChristosDav** [comment]
Generaly I was thinking something that can add a satisfying feel to collecting the following items. Maybe this can be a cool sfx or a vfx.


- The map of each location.

- Keys with a Theoris logo engraving for unlocking the cabinets.

- Paper notes with codes for unlocking the cabinets.

- Athena’s diary pages (?). I’m a bit skeptical about it because I sometimes find them boring in a game.

- Collectable variations based on locations. What could be the possible rewards for these?

   1. _Laboratory_: Blood vials.

   2. _Cemetery_: Rare flowers that are grown next to the tombs.

   3. _Morgue_: Toe tags.

Regarding the diary pages, Andrew suggested that we should have just regular notes from scientists, rather than Athena's. A possible idea is to have Athena's diary pages, explaining her plan to get revenge from the Organization. And if we go with the scientists notes, we can have something like a log on the experiments that they conducted.

What do you think?

**Comment by Unicornosplendente** [comment]
I close this task couse according to Baha is a bit outdate

fyi @alexitsios @crtherin
