### ISSUE TITLE
Define the items of the interface (health, inventory, status information, etc)

### ISSUE THREAD

**Issue by alexitsios** [alexitsios/Calamity#52]

**Comment by teberzin** [comment]
We will use the no-hud approach, which has more cinematographic flow. Health status and ammo will only be visible through inventory (health has an in-game representation as changing animation for different statuses though). If you're asking for the other interface such as for the inventory. I think rather than me GUI has to answer this task.

**Comment by alexitsios** [comment]
@teberzin GUI guy will need to know the iteams that'll be used. etc health bar, status of health bar, inventory items etc. That's what we need before the GUI guy starts working on them. Let me know if you want more clarifying.

**Comment by teberzin** [comment]
@alexitsios Nop totally it makes sense but more than definitions I can just create the tasks for the GUI artist when we have him. I mean I can make the things that we will need in the UI but I think it will just be too short to even create a page :D So better to just directly communicate with the artist instead. If you think it's better to keep written I can write please let me know ^^.

**Comment by alexitsios** [comment]
No problem. Whatever you think works best.
